(function() {var implementors = {};
implementors["mbox"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"mbox/sentinel/trait.Sentinel.html\" title=\"trait mbox::sentinel::Sentinel\">Sentinel</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">[</a>T<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">]</a>&gt; for <a class=\"struct\" href=\"mbox/sentinel/struct.MArray.html\" title=\"struct mbox::sentinel::MArray\">MArray</a>&lt;T&gt;",synthetic:false,types:["mbox::sentinel::MArray"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"mbox/sentinel/struct.MString.html\" title=\"struct mbox::sentinel::MString\">MString</a>",synthetic:false,types:["mbox::sentinel::MString"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"mbox/sentinel/struct.MString.html\" title=\"struct mbox::sentinel::MString\">MString</a>",synthetic:false,types:["mbox::sentinel::MString"]},{text:"impl&lt;T:&nbsp;?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> + <a class=\"trait\" href=\"mbox/free/trait.Free.html\" title=\"trait mbox::free::Free\">Free</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;T&gt; for <a class=\"struct\" href=\"mbox/mbox/struct.MBox.html\" title=\"struct mbox::mbox::MBox\">MBox</a>&lt;T&gt;",synthetic:false,types:["mbox::mbox::MBox"]},];
implementors["utf8_cstr"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"utf8_cstr/struct.Utf8CStr.html\" title=\"struct utf8_cstr::Utf8CStr\">Utf8CStr</a>",synthetic:false,types:["utf8_cstr::Utf8CStr"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>&gt; for <a class=\"struct\" href=\"utf8_cstr/struct.Utf8CStr.html\" title=\"struct utf8_cstr::Utf8CStr\">Utf8CStr</a>",synthetic:false,types:["utf8_cstr::Utf8CStr"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
